import type { MemberChangeEventRow } from "./map-member-core";

const CATEGORY_CHIPS = [
	"Member Identifiers",
	"Name",
	"Date of Birth",
	"Gender",
	"Address",
	"Eligibility Status",
	"Coverage/Plan",
	"Dependents",
	"Contact Information",
	"Other",
] as const;

export type ChangeEventCategoryFilter = (typeof CATEGORY_CHIPS)[number] | "all";

const MOCK_EVENTS: Omit<MemberChangeEventRow, "id">[] = [
	{
		changeDate: "08/28/2026 12:41 PM",
		changeType: "Update",
		category: "Member Identifiers",
		fieldName: "NewTech Member ID",
		fieldReason: "Reason: System update from source file",
		oldValue: "—",
		newValue: "12345678",
		reason: "NewTech crosswalk refresh",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "08/28/2026",
	},
	{
		changeDate: "08/28/2026 12:41 PM",
		changeType: "Update",
		category: "Member Identifiers",
		fieldName: "Cardholder ID",
		fieldReason: "Reason: System update from source file",
		oldValue: "DEMO0001",
		newValue: "099898779",
		reason: "Member ID standardization",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "08/28/2026",
	},
	{
		changeDate: "08/27/2026 4:15 PM",
		changeType: "Update",
		category: "Eligibility Status",
		fieldName: "Eligibility Status",
		fieldReason: "Reason: Annual eligibility refresh",
		oldValue: "Pending",
		newValue: "Eligible",
		reason: "Verified eligible from source file",
		changedBy: "MDH Eligibility System",
		source: "NHI Eligibility System",
		effectiveDate: "08/27/2026",
	},
	{
		changeDate: "08/25/2026 9:02 AM",
		changeType: "Update",
		category: "Coverage/Plan",
		fieldName: "Current Plan",
		fieldReason: "Reason: Open enrollment change",
		oldValue: "MDH CareFirst HMO",
		newValue: "MDH CareFirst PPO - Employee + Children",
		reason: "Plan selection during open enrollment",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "01/01/2026",
	},
	{
		changeDate: "08/22/2026 2:30 PM",
		changeType: "Update",
		category: "Address",
		fieldName: "Mailing Address",
		fieldReason: "Reason: Member address update",
		oldValue: "123 Oak St, Baltimore, MD 21201",
		newValue: "456 Maple Ave, Baltimore, MD 21202",
		reason: "Address correction from member portal",
		changedBy: "Member Portal",
		source: "Member Self-Service",
		effectiveDate: "08/22/2026",
	},
	{
		changeDate: "08/18/2026 11:20 AM",
		changeType: "Add",
		category: "Dependents",
		fieldName: "Dependent",
		fieldReason: "Reason: New dependent added",
		oldValue: "—",
		newValue: "Bethel Abebe (Child)",
		reason: "Birth certificate received",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "08/01/2026",
	},
	{
		changeDate: "08/10/2026 8:45 AM",
		changeType: "Update",
		category: "Contact Information",
		fieldName: "Phone Number",
		fieldReason: "Reason: Contact update",
		oldValue: "(410) 555-0100",
		newValue: "(410) 555-0199",
		reason: "Updated contact from eligibility file",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "08/10/2026",
	},
	{
		changeDate: "07/28/2026 3:12 PM",
		changeType: "Update",
		category: "Name",
		fieldName: "Middle Name",
		fieldReason: "Reason: Legal name correction",
		oldValue: "—",
		newValue: "Marie",
		reason: "Legal documentation received",
		changedBy: "MDH Operations",
		source: "Manual Update",
		effectiveDate: "07/28/2026",
	},
	{
		changeDate: "07/15/2026 10:00 AM",
		changeType: "Update",
		category: "Date of Birth",
		fieldName: "Date of Birth",
		fieldReason: "Reason: DOB verification",
		oldValue: "06/01/2015",
		newValue: "06/02/2015",
		reason: "Corrected from birth certificate",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "06/02/2015",
	},
	{
		changeDate: "07/01/2026 1:05 PM",
		changeType: "Update",
		category: "Gender",
		fieldName: "Gender",
		fieldReason: "Reason: Demographic standardization",
		oldValue: "Unknown",
		newValue: "Female",
		reason: "Standardized from source file",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "07/01/2026",
	},
	{
		changeDate: "06/20/2026 9:30 AM",
		changeType: "Update",
		category: "Member Identifiers",
		fieldName: "External ID",
		fieldReason: "Reason: Crosswalk update",
		oldValue: "87654320",
		newValue: "87654321",
		reason: "External ID crosswalk refresh",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "06/20/2026",
	},
	{
		changeDate: "06/05/2026 4:50 PM",
		changeType: "Update",
		category: "Eligibility Status",
		fieldName: "Coverage Tier",
		fieldReason: "Reason: Tier change",
		oldValue: "Employee Only",
		newValue: "Employee + Children",
		reason: "Dependent added — tier updated",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "06/05/2026",
	},
	{
		changeDate: "05/12/2026 2:18 PM",
		changeType: "Update",
		category: "Contact Information",
		fieldName: "Email",
		fieldReason: "Reason: Contact update",
		oldValue: "lily.n@example.com",
		newValue: "lily.nguyen@email.com",
		reason: "Email updated from member portal",
		changedBy: "Member Portal",
		source: "Member Self-Service",
		effectiveDate: "05/12/2026",
	},
	{
		changeDate: "04/22/2026 11:05 AM",
		changeType: "Add",
		category: "Other",
		fieldName: "PCP Assignment",
		fieldReason: "Reason: PCP auto-assignment",
		oldValue: "—",
		newValue: "Dr. Sarah Chen (NPI 1234567890)",
		reason: "Auto-assigned based on zip code",
		changedBy: "MDH Eligibility System",
		source: "NHI Eligibility System",
		effectiveDate: "04/22/2026",
	},
	{
		changeDate: "03/15/2026 8:00 AM",
		changeType: "Update",
		category: "Coverage/Plan",
		fieldName: "Group Number",
		fieldReason: "Reason: Employer group change",
		oldValue: "GRP-1001",
		newValue: "GRP-2045",
		reason: "Employer group reassignment",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "01/01/2026",
	},
	{
		changeDate: "02/28/2026 3:40 PM",
		changeType: "Update",
		category: "Address",
		fieldName: "County",
		fieldReason: "Reason: Geocoding update",
		oldValue: "Baltimore City",
		newValue: "Baltimore County",
		reason: "County corrected via geocoding",
		changedBy: "MDH Eligibility System",
		source: "NHI Eligibility System",
		effectiveDate: "02/28/2026",
	},
	{
		changeDate: "01/15/2026 10:22 AM",
		changeType: "Add",
		category: "Member Identifiers",
		fieldName: "Alternate ID",
		fieldReason: "Reason: Alternate ID assigned",
		oldValue: "—",
		newValue: "64987572",
		reason: "Alternate ID generated at enrollment",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "01/01/2026",
	},
	{
		changeDate: "12/10/2025 9:15 AM",
		changeType: "Update",
		category: "Eligibility Status",
		fieldName: "Member Status",
		fieldReason: "Reason: Status activation",
		oldValue: "Pending",
		newValue: "Active",
		reason: "Enrollment completed",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "01/01/2026",
	},
	{
		changeDate: "11/20/2025 2:00 PM",
		changeType: "Add",
		category: "Coverage/Plan",
		fieldName: "Enrollment",
		fieldReason: "Reason: Initial enrollment",
		oldValue: "—",
		newValue: "MDH CareFirst HMO",
		reason: "New member enrollment",
		changedBy: "NHI Eligibility",
		source: "NHI Eligibility System",
		effectiveDate: "01/01/2026",
	},
];

export function buildMockMemberChangeEvents(
	memberId: string
): MemberChangeEventRow[] {
	return MOCK_EVENTS.map((event, index) => ({
		...event,
		id: `${memberId}-ce-${index + 1}`,
	}));
}

export { CATEGORY_CHIPS };

export function summarizeChangeEvents(rows: MemberChangeEventRow[]) {
	const now = new Date("2026-08-28T12:41:00");
	const thirtyDaysAgo = new Date(now);
	thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

	const last30 = rows.filter((row) => {
		const d = new Date(row.changeDate);
		return !Number.isNaN(d.getTime()) && d >= thirtyDaysAgo;
	});

	const uniqueFields = new Set(rows.map((r) => r.fieldName));

	return {
		total: rows.length,
		last30Days: last30.length,
		last30TrendPct: 20,
		mostRecent: rows[0]?.changeDate ?? "—",
		changedBy: rows[0]?.changedBy ?? "—",
		uniqueChangeTypes: uniqueFields.size,
	};
}
